version: "3.8"
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - logs:/app/logs
            - ./backend:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/app/src
        stdin_open: true
        tty: true
        depends_on:
            - backend
volumes:
    logs:
