POST http://localhost:5000/api/data_db/addNewData
Content-Type: application/json

{
  
}

###

POST http://localhost:5000/api/data_db/getData
Content-Type: application/json

{

}

###
POST http://localhost:5000/api/user/register
Content-Type:  application/json

{
  "firstName": "abec",
  "lastName": "asldkfj",
  "email":"exampleeee@com.com",
  "password": "Qwerty1234!"
}
###

GET http://localhost:5000/api/download/json

###

POST http://localhost:5000/api/user/register
Content-Type:  application/json

{
  "firstName": "abec",
  "lastName": "asldkfj",
  "email":"exampleeee@com.com",
  "password": "Qwerty1234!"
}

###

get http://localhost:5000/api/general/getData