POST http://localhost:5000/api/data_db/crypto/addNewData
Content-Type: application/json

{
    "crypto":{
    "cryptoName": "Bitcoin",
    "prices":[
      {"date":"2013-04-29","price":2866.95},
      {"date":"2014-04-29","price":3866.95},
      {"date":"2015-04-29","price":4866.95}
    ]
    }
}

###
POST http://localhost:5000/api/user/register
Content-Type:  application/json

{
  "firstName": "abec",
  "lastName": "asldkfj",
  "email":"exampleeee@com.com",
  "password": "Qwerty1234!"
}
###

GET http://localhost:5000/api/data_api

###

POST http://localhost:5000/api/user/register
Content-Type:  application/json

{
  "firstName": "abec",
  "lastName": "asldkfj",
  "email":"exampleeee@com.com",
  "password": "Qwerty1234!"
}